### ISSUE TITLE
Dependencies and self-declaration

### ISSUE THREAD

**Issue by bernhardreiter** [matrixise/dsmtpd#2]
Hi Stephane,
thanks for publishing Free Software, I've just added some dsmtpd instructions to
intelmq-mailgen's readme, I've done the selection in https://github.com/Intevation/intelmq-mailgen/issues/15

I've notice a few thing that could improve the experience for others:
- changing the self description at https://pypi.python.org/pypi/dsmtpd/0.2.2 to something more stable and python3 would have been helpful to me to faster see the benefits of the package
- I did not want to use "pip install" for a small package like this, maybe you can include support or instructions how to use it directly if it isn't installed. (I've ended up using `python3 -c 'from dsmtpd._dsmtpd import *; main()'`) I would have expected something like python3 -m dsmtpd...
- Using the docopt dependency in my view is a bit too much for a little debugging server, I would have wanted it as close as I can get to smtpd.DebuggingServer and no dependencies. The three parameters
  would have been fine with some optparse or argparse directly from python as well. (It is probably subject to discussion what the better opt parser is, but having one more dependency is a drawback.)

Thanks again and 
Best Regards,
Bernhard

**Comment by matrixise** [comment]
Hi Bernhard,

Sorry, I was not really available during june and july.
thank you for your feedback,

Stephane

**Comment by bernhardreiter** [comment]
Hi Stephane,
no problem!
Thanks for creating Free Software!

**Comment by matrixise** [comment]
Hi @bernhardreiter 

Migration to aiosmtp and python3, are you interested in the project, or is it too late for you?

Thank you

**Comment by matrixise** [comment]
Hi @bernhardreiter 

I read your suggestions which I found interesting, I modified the code according to them.

Thank you for your contribution

**Comment by bernhardreiter** [comment]
Hi @matrixise 

> Migration to aiosmtp and python3, are you interested in the project

as we still use dsmtpd as debugging server in one place, we'd still need the functionality.
(You've guessed this, when seeing the last commit on my branch I guess. ;) )

Overall it probably could need a new release now (0.3.0 or 1.0.0) and then a reimplementation based on the recommended 
 (https://docs.python.org/3.6/library/smtpd.html) would make it more future proof. So I'm "interested" if this is what you mean by it.

(If I'd do a fresh implementation myself I'd probably go to https://foss.heptapod.net/ for hosting or at least gitlab. >;) )

Best Regards,
Bernhard

**Comment by matrixise** [comment]
Hi @bernhardreiter I don't work on the SMTPUTF8 stuff, but I have updated a lot of things in the code. You should have a 0.3 on this after-noon. Also, I think to add a roadmap, do you want to help?

**Comment by bernhardreiter** [comment]
@matrixise thanks for asking! Unfortunately I cannot really devote much time to helping, so I'd better not agree to it. My company is willing to do a small donation, if you want.

**Comment by matrixise** [comment]
@bernhardreiter thanks, https://pypi.org/project/dsmtpd/0.3/ has been released.

**Comment by bernhardreiter** [comment]
Very cool! 
(Ah, maybe the copyright 2013 -> 2021 in the example call and at the bottom)

**Comment by matrixise** [comment]
yep, why not. I will add github actions for the future releases, etc... Have a nice day and thank you for your contribution.

Stéphane

**Comment by bernhardreiter** [comment]
A nice day and thanks to you, too.

Bernhard
